### PR TITLE
Add  some notes about PointsBot

### PR DESCRIPTION
**Pull request by mattstabeler**
Added a purpose and background to the README

### CODE REVIEW

**Review by Alonski — COMMENTED** [review]
This is awesome! I'll take a better look at this tomorrow but looks really cool!

**Comment by Quazia** [comment]
Looks awesome! 25 SC points.

**Review by Alonski — APPROVED** [review]
Love it!

**Comment by Alonski** [comment]
@Quazia I wanted to suggest some SC points for @mattstabeler 
Thanks!

**Pull request merged**
